### ISSUE TITLE
InfinitePermutationSourceIterator + distributed training + shuffle

### ISSUE THREAD

**Issue by scarecrow1123** [microsoft/infinibatch#31]
Is it safe to do distributed training with `InfinitePermutationSourceIterator` with `shuffle=True`? On a cursory glance at the [class's source](https://github.com/microsoft/infinibatch/blob/f1eea7c9943caf20472d868b5fcf916422522356/infinibatch/iterators.py#L440), there isn't any handling based on `instance_rank` to properly distribute the shards across instances and this could lead to same chunks being read by different data loading processes in a distributed setting. A clarification on how to properly use this in a distributed setting would be great!

edit: fix typo

**Comment by gmyr** [comment]
Define "safe". :-)

[This line](https://github.com/microsoft/infinibatch/blob/f1eea7c9943caf20472d868b5fcf916422522356/infinibatch/iterators.py#L442) effectively causes the chunks / shards to be distributed across GPUs.

Intuitively, `InfinitePermutationSourceIterator` generates an infinite sequence of permutations of the given list of source items. For example, if `source_items = [1, 2, 3]` then the iterator operates on an infinite sequence such as
```[1, 3, 2, 2, 1, 3, 3, 2, 1, 1, 2, 3, ...]```,
and different instances / GPUs will go through this list in strides: An instance with rank `r` will start with the element at index `i = r` in this infinite sequence and then increment the index by the number of instance `i = i + num_instances`.

So if you have 2 instances and you operate on the example sequence above, you would get the following sequences:

instance 0: `[1, 2, 1, 3, 1, 2, ...]`
instance 1: `[3, 2, 3, 2, 1, 3, ...]`

As you can see, it generally can happen that two instances get the same item in the same step. To guarantee that this doesn't happen, you would need that `len(source_items) % num_instances == 0`. However, you typically want to use this iterator only as a first level of shuffling and supplement it with a second level of shuffling __across chunks__ with an iterator such as the `BlockwiseShuffleIterator`. For example, let's say you train on 100 chunks that are text-files containing 10k sentences each. Then `InfinitePermutationSourceIterator` would shuffle the chunk files, you would want to use a `SelectManyIterator` to read the lines from the shuffled chunks, and you would want to use a `BlockwiseShuffleIterator` with a `block_size` that spans a couple of chunks, for example `block_size = 50000`, to shuffle sentences across different chunks. That way, even if two GPUs happen to get the same chunk at some point, the `BlockwiseShuffleIterator` would make it very unlikely that the GPUs train on the same example in a specific step.

**Comment by scarecrow1123** [comment]
@gmyr I just realized that I've missed to reply here. Apologies for the delayed response. My original issue was getting duplicate data samples across GPUs in a distributed setup and hence the query.

> To guarantee that this doesn't happen, you would need that len(source_items) % num_instances == 0

This is the condition that wasn't met in my training setup and handling it with the correct number of `source_items` has helped fixing the problem. Your detailed response is much appreciated.
