### ISSUE TITLE
Why is setup.py empty?

### ISSUE THREAD

**Issue by erip** [microsoft/infinibatch#4]
The project looks great, but manipulating the `PYTHONPATH` or appending paths to the `sys.path` at runtime is a bit unconventional. 😄 I think populating the `setup.py` could make this a bit more easy to install. WDYT?

**Comment by erip** [comment]
I'm also happy to provide a minimal setup.py if that would help.

**Comment by frankseide** [comment]
That would be super-helpful! We are not too familiar with the setup process. Thanks!!

**Comment by erip** [comment]
Absolutely. I'll submit a PR soon. There's authorship information that's typically required as a part of the setuptools process, but I'll can use your name, @frankseide, and will let you fix it up as a part of the merge as you see most appropriate.

**Comment by frankseide** [comment]
Thanks!

**Comment by frankseide** [comment]
PR merged. Thanks for your contribution!
